server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eureka?useSSL=false&serverTimezone=UTC
    username: root
    password: Root123!
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: service
  main:
    allow-bean-definition-overriding: true #当遇到相同名字时，是否允许覆盖注册

eureke:
  client:
    service-url: #EurekaServer地址
      defaultZone: http://127.0.0.1:8761/eureka

  instance:
    prfer-ip-address: true #当调用getHoustname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 #指定自己的ip信息，不指定的话会自己寻找
