server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eureka?useSSL=false&serverTimezone=UTC
    username: root
    password: Root123!
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: consumer #应用名称
eureka:
  client:
    service-url: #EurekaServer地址
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
